config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  get 'events/index'
  
  devise_for :users
  
  root 'events#index'
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
#un event rassemble plusieurs personnes
has_many :attendances
has_many :users, through: :attendances
#un event a un administrateur : à coder
belongs_to :admin, class_name: "User"

validate :divisible_by_five, :is_in_future?

validates :start_date, 
    presence: {message: "Merci de saisir une date !"} #,
    #if is_in_the_futur?
    #il est impossible de créer ou modifier un événement dans le passé.
    validates :duration, 
    presence: {message: "Merci de saisir une durée !"}
    validates :title, 
    presence: {message: "Merci de saisir un titre !"},
    length: {minimum: 5, maximum: 140, message: "Le titre doit être entre 5 et 140 caractères"}
    validates :description, 
    presence: {message: "Merci de saisir un contenu !"},
    length: {minimum: 20, maximum: 1000, message: "La description doit être entre 20 et 1000 caractères"}
    validates :price,
    presence: {message: "Merci de saisir un prix !"},
    numericality: { in: 1..1000 }
    validates :location, 
    presence: {message: "Merci de saisir une ville !"}


    def divisible_by_five
      if (self.duration % 5) != 0
        self.errors[:base] << "La durée doit être un multiple de 5"
      end
    end

    def is_in_future?
      self.start_date  >=  Date.today
    end
  end



	# validates :start_date, presence: true
	# validate :is_in_future
	# validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
	# validate :divisible_by_five
	# validates :title, presence: true, length: { in: 5..140 }
	# validates :description, presence: true, length: { in: 20..1000 }
	# validates :price, presence: true, numericality: { in: 1..1000 }
	# validates :location, presence: true

	# def divisible_by_five
	#  	if (self.duration % 5) != 0
	#       self.errors[:base] << "Le prix doit être divisible par 5 !"
	#    	end
 # 	end

 # 	def is_in_future
	#  	if self.start_date < Time.now
	#       self.errors[:base] << "La date doit être postérieure au moment présent !"
	#    	end
 # 	end
# end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
#relation à plusieurs events comme participant
	has_many :attendances
	has_many :events, through: :attendances


	after_create :welcome_send

	def welcome_send
	  UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]

  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
  end

  def show
    # @user=User.find_by(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!-- <h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>
-->
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<div class="container">
		<h2 class="display-3">EventBrite Saint-Denis</h2>
		<p>Voici la liste des événements prévus à Saint-Denis!</p>
		<p><a class="btn btn-primary btn-lg" href="#" role="button">Créer un nouvel événement »</a></p>
	</div>
</div>

<div class="container">
	<!-- row of columns -->
	<div class="row">

		<!-- Affichage des events dans des cards -->
		<% Event.all.each do |e| %>

		<div class="col-md-4">
			<div class = "card-deck">
				<div class="card bg-light mb-3 border-secondary" style="width: 20%;">
					<img class="card-img-top" src="https://www.agence-evenementielle-innovevents.fr/wp-content/uploads/2019/02/lieux-evenements-entreprise-marseille-672x372.jpg" alt="event marseille">
					<div class="card-body text-center">
						<h5 class="card-title"><%= e.title %></h5>
						<p class="card-text"><%= e.description %></p>
					</div>
					<ul class="list-group list-group-flush">
						<li class="list-group-item"><%= e.start_date %></li>
					</ul>
					<div class="card-body">
						<a href="#" class="card-link">Voir détails</a>
					</div>
				</div>
			</div>
		</div>

		<% end %>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thpeventbrite</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark" style="background-color: #e3f2fd;">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" <%= link_to "Accueil", root_path %> </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Créer en événement" %></a>
          </li>
        </ul>

        <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li> <%= current_user.first_name %> <%= current_user.last_name %> </li>
        </ul>
        <% end %>

        <ul class="navbar-nav mr-rg">
        <form class="form-inline my-2 my-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Mon profil", user_path(current_user.id) %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to('Se déconnecter', destroy_user_session_path, method: :delete) %></a>
          </li>
         <% else %>
         <li class="nav-item">
           <a class="nav-link" <%= link_to "S'inscrire",  new_user_registration_path %></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" <%= link_to "Se connecter", new_user_session_path %></a>
         </li>
         <% end %>
        </form>
        </ul>

      </div>
    </nav>
  </head>

  <body>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
  <li>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  </li>

  <li>
    Voici ton email : <%= current_user.email %>
  </li>

  <li>
    <%= link_to "Secret page", static_pages_secret_path %>
  </li>

  <li>
    <%= link_to "Edit email / password", edit_user_registration_path %>
  </li>

  <% else %>
  <li>    
    <%= link_to "Sign in", new_user_session_path %>
  </li>

  <li>
    <%= link_to "Sign up", new_user_registration_path %>
  </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>